In [132]:
import numpy as np
import scipy 
import re

In [133]:
txt_open = open('sentences.txt')
data_txt = txt_open.readlines()
txt_open.close()

In [134]:
print(data_txt)

['In comparison to dogs, cats have not undergone major changes during the domestication process.\n', 'As cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.\n', 'A common interactive use of cat for a single file is to output the content of a file to standard output.\n', 'Cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.\n', 'In one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.\n', 'The domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.\n', 'Domestic cats are similar in size to the other members of the genus Felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).\n', 'However, if the output is piped or redirected, cat is unnecessary.\n', 'cat with one named file is safer where human

In [135]:
filtered_sentences = []

for item in data_txt:
    low_words = re.split('[^a-z]', item.lower())
    filtered_sentences.append(list(filter(None,  low_words)))

num_of_sentences = len(filtered_sentences)

In [136]:
print(num_of_sentences)
print(filtered_sentences)

22
[['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process'], ['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes'], ['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output'], ['cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals'], ['in', 'one', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin'], ['the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organ

In [137]:
words_dict = {}
i = 0

for sentence in filtered_sentences:
    for word in sentence:
        if word not in words_dict:
            words_dict[word] = i
            i += 1

num_of_words = len(words_dict)

In [138]:
print(num_of_words)
print(words_dict)

254
{'in': 0, 'comparison': 1, 'to': 2, 'dogs': 3, 'cats': 4, 'have': 5, 'not': 6, 'undergone': 7, 'major': 8, 'changes': 9, 'during': 10, 'the': 11, 'domestication': 12, 'process': 13, 'as': 14, 'cat': 15, 'simply': 16, 'catenates': 17, 'streams': 18, 'of': 19, 'bytes': 20, 'it': 21, 'can': 22, 'be': 23, 'also': 24, 'used': 25, 'concatenate': 26, 'binary': 27, 'files': 28, 'where': 29, 'will': 30, 'just': 31, 'sequence': 32, 'a': 33, 'common': 34, 'interactive': 35, 'use': 36, 'for': 37, 'single': 38, 'file': 39, 'is': 40, 'output': 41, 'content': 42, 'standard': 43, 'hear': 44, 'sounds': 45, 'too': 46, 'faint': 47, 'or': 48, 'high': 49, 'frequency': 50, 'human': 51, 'ears': 52, 'such': 53, 'those': 54, 'made': 55, 'by': 56, 'mice': 57, 'and': 58, 'other': 59, 'small': 60, 'animals': 61, 'one': 62, 'people': 63, 'deliberately': 64, 'tamed': 65, 'artificial': 66, 'selection': 67, 'they': 68, 'were': 69, 'useful': 70, 'predators': 71, 'vermin': 72, 'domesticated': 73, 'its': 74, 'closes

In [139]:
matrix = np.zeros((num_of_sentences, num_of_words))  
        
for index, sentence in enumerate(filtered_sentences):
    for word in sentence:
        matrix[index][words_dict[word]] = sentence.count(word)

In [140]:
print(matrix.shape)
print(matrix)

(22, 254)
[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 1. 1.]]


In [141]:
from scipy.spatial import distance

distances = []

for i in range(num_of_sentences): 
    distances.append(distance.cosine(matrix[0], matrix[i]))
    
dist_copy = distances.copy() 
dist_copy.remove(0)

In [142]:
first_index = distances.index(min(dist_copy))
dist_copy.remove(dist_copy[first_index - 1])
second_index = distances.index(min(dist_copy))

print(first_index, second_index)
print(distances[first_index], distances[second_index])

6 4
0.7327387580875756 0.7770887149698589


In [143]:
file = open('solution.txt', 'w')
file.write(str(first_index) + " ")
file.write(str(second_index))
file.close()

In [158]:
dist = distances.copy()
dist.sort()
#index = distances.index(dist[???])  ??? - choose index more 2

In [159]:
print(distances[index])
print(index)

0.8406361854220809
16
